// Verin Legal — record archives and reports.
//
//   exportRecordZip          One matter, standalone-verifiable: manifest.json,
//                            exhibits/ (files exactly as received),
//                            timestamps/*.tsr (RFC 3161 tokens),
//                            certificate.pdf, verify.py, README.txt.
//   exportFirmData           Every matter's manifest in one ZIP (no exhibits).
//   exportIntegrationReport  PDF: what was synced to each practice system,
//                            item by item, with hashes.

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { PassThrough } = require('stream');
const { getApps, initializeApp } = require('firebase-admin/app');
const { getFirestore, FieldValue } = require('firebase-admin/firestore');
const { getStorage } = require('firebase-admin/storage');
const { onCall, HttpsError } = require('firebase-functions/v2/https');

const P = require('../common/params');
const { requireAuth, loadMatterForUser, firmIdForUser } = require('../common/access');
const { verifyEntries } = require('../chain/chain');
const { buildRecordPdf, printable, human, dash, FONTS, COLORS } = require('./record_pdf');

if (!getApps().length) initializeApp();

const toDate = (v) => (v && typeof v.toDate === 'function' ? v.toDate() : v instanceof Date ? v : null);
const isoOrNull = (v) => {
  const d = toDate(v);
  return d ? d.toISOString() : null;
};

function slug(s) {
  return (
    String(s || 'matter')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'matter'
  );
}

function safeName(s) {
  return String(s || 'file').replace(/[\\/:*?"<>|\u0000-\u001f]/g, '_').slice(0, 120);
}

function headlineOf(r) {
  if (r.content) return r.content;
  const kind = r.itemKind ? r.itemKind.replace(/_/g, ' ') : 'Item';
  return r.channel ? `${kind} via ${r.channel}` : kind;
}

/// Pure: builds the manifest object from plain matter / receipt / chain data.
/// receipts: [{ id, data }]; chain: [entry data]. exhibitFor(receipt) -> path or null.
function buildManifest({ matterId, matter, receipts, chain, exportedAt, exportedBy, exhibitFor, tsrFor }) {
  const sortedChain = [...chain].sort((a, b) => (a.seq || 0) - (b.seq || 0));
  const verification = verifyEntries(sortedChain);
  return {
    format: 'verin-record-manifest',
    format_version: 1,
    exported_at: exportedAt.toISOString(),
    exported_by: exportedBy,
    hash_algorithm: 'SHA-256',
    chain_formula: 'entry_hash = SHA256(prev_hash + "|" + item_hash + "|" + received_at + "|" + origin_digest); first prev_hash = 64 zeros',
    matter: {
      id: matterId,
      name: matter.matterName || matter.caseTitle || '',
      client: matter.clientName || '',
      cause_number: matter.caseNumber || '',
      practice_area: matter.practiceArea || matter.matterType || '',
      status: matter.status || '',
      opened_at: isoOrNull(matter.openedAt),
      archive_build: matter.isArchiveBuild === true,
    },
    chain_head: matter.chainHeadHash || verification.head || null,
    chain_verification_at_export: {
      ok: verification.ok,
      verified_entries: verification.verified,
      legacy_entries: verification.legacy,
      broken_at: verification.brokenAt || null,
      reason: verification.reason || null,
    },
    receipts: receipts
      .map(({ id, data: r }) => ({
        id,
        received_at: isoOrNull(r.receivedAt),
        channel: r.channel || '',
        from: r.fromLabel || '',
        item_kind: r.itemKind || '',
        content: headlineOf(r),
        original_file_name: r.originalFileName || '',
        content_type: r.contentType || '',
        size_bytes: r.sizeBytes || null,
        item_hash: r.item_hash || '',
        chain_seq: r.chainSeq || null,
        entry_hash: r.entryHash || '',
        state: r.classificationLabel || '',
        is_duplicate: r.isDuplicate === true,
        origin_fidelity: r.originFidelity || null,
        duration_seconds: r.durationSeconds || null,
        evidence_date: isoOrNull(r.resolvedDate),
        evidence_date_confidence: r.dateConfidence || null,
        evidence_date_source: r.dateSource || null,
        rfc3161: r.tsaGenTime ? { tsa: r.tsaName || '', gen_time: isoOrNull(r.tsaGenTime), token_file: tsrFor ? tsrFor({ id, data: r }) : null } : null,
        exhibit_file: exhibitFor ? exhibitFor({ id, data: r }) : null,
        description: r.description || '',
        chain_of_custody_notes: r.custodyNotes || '',
        ai_reading: r.aiSummary ? { summary: r.aiSummary, note: 'Reading aid generated by AI; cites the exhibit and never replaces it.' } : null,
      }))
      .sort((a, b) => String(a.received_at).localeCompare(String(b.received_at))),
    chain: sortedChain.map((e) => ({
      seq: e.seq || 0,
      prev_hash: e.prevHash || null,
      item_hash: e.itemHash || null,
      received_at: e.receivedAtIso || null,
      origin_digest: e.originDigest || null,
      entry_hash: e.entryHash || null,
    })),
  };
}

function readmeText(manifest) {
  return [
    'VERIN EVIDENCE RECORD',
    '',
    `Matter:       ${manifest.matter.name}`,
    `Exported:     ${manifest.exported_at}`,
    `Chain head:   ${manifest.chain_head || '-'}`,
    '',
    'Contents',
    '  manifest.json     every receipt with its SHA-256 at receipt, and the hash chain',
    '  exhibits/         the files exactly as received (named <chain #>-<original name>)',
    '  timestamps/       RFC 3161 timestamp tokens over each item hash (.tsr)',
    '  certificate.pdf   Certificate of Preparation with the itemized exhibit index',
    '  verify.py         standalone verifier (Python 3, standard library only)',
    '',
    'To verify',
    '  1. Unzip this archive.',
    '  2. Run:  python3 verify.py',
    '  3. PASS means every exhibit hashes to the value recorded at receipt and the',
    '     hash chain recomputes to the chain head above. A failure names the first',
    '     broken link.',
    '',
    'Timestamps can be inspected with OpenSSL:  openssl ts -reply -in timestamps/<file>.tsr -text',
    '',
    'The record shows what arrived and when. It does not describe what happened to',
    'a file before it arrived. Verin offers no opinion on authenticity, completeness',
    'or admissibility; those determinations belong to counsel and the Court.',
    '',
  ].join('\n');
}

function makeZip() {
  const archiver = require('archiver');
  const zip = archiver('zip', { zlib: { level: 6 } });
  const out = new PassThrough();
  zip.pipe(out);
  return { zip, out };
}

// Adds one streamed entry and waits until archiver has written it, so only
// one exhibit is being downloaded at a time (exhibits can be up to 2 GB).
function appendAndWait(zip, openStream, name) {
  return new Promise((resolve, reject) => {
    const onEntry = (entry) => {
      if (entry.name === name) {
        zip.removeListener('entry', onEntry);
        zip.removeListener('error', onError);
        resolve();
      }
    };
    const onError = (e) => {
      zip.removeListener('entry', onEntry);
      reject(e);
    };
    zip.on('entry', onEntry);
    zip.once('error', onError);
    const stream = openStream();
    stream.on('error', onError);
    zip.append(stream, { name });
  });
}

async function saveStream(bucket, storagePath, out, contentType, fileName, uid) {
  const token = crypto.randomUUID();
  const hash = crypto.createHash('sha256');
  let bytes = 0;
  out.on('data', (c) => {
    hash.update(c);
    bytes += c.length;
  });
  await new Promise((resolve, reject) => {
    out
      .pipe(
        bucket.file(storagePath).createWriteStream({
          resumable: false,
          contentType,
          metadata: { contentDisposition: `attachment; filename="${fileName}"`, metadata: { firebaseStorageDownloadTokens: token, generatedBy: uid } },
        }),
      )
      .on('finish', resolve)
      .on('error', reject);
  });
  return {
    sha256: hash.digest('hex'),
    bytes,
    downloadUrl: `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(storagePath)}?alt=media&token=${token}`,
  };
}

async function loadMatterData(db, ref) {
  const [receiptSnap, chainSnap] = await Promise.all([
    db.collection('Receipts').where('matterId', '==', ref).get(),
    db.collection('chainEntries').where('matterID', '==', ref).get(),
  ]);
  return {
    receipts: receiptSnap.docs.map((d) => ({ id: d.id, data: d.data() })),
    chain: chainSnap.docs.map((d) => d.data()),
  };
}

async function generatedByName(db, uid, request) {
  const user = await db.collection('users').doc(uid).get();
  return (user.exists && (user.get('display_name') || user.get('email'))) || (request.auth.token && request.auth.token.email) || uid;
}

function pdfReceipts(receipts) {
  return receipts
    .map(({ id, data: r }) => ({
      id,
      receivedAt: toDate(r.receivedAt),
      channel: r.channel || '',
      itemKind: r.itemKind || '',
      headline: headlineOf(r),
      itemHash: r.item_hash || '',
      entryHash: r.entryHash || '',
      chainSeq: r.chainSeq || 0,
      detectedPlatform: r.detectedPlatform || '',
      threadMessages: Array.isArray(r.threadMessages) ? r.threadMessages : [],
    }))
    .sort((a, b) => (a.receivedAt ? a.receivedAt.getTime() : 0) - (b.receivedAt ? b.receivedAt.getTime() : 0));
}

exports.exportRecordZip = onCall({ timeoutSeconds: 540, memory: '2GiB' }, async (request) => {
  const uid = requireAuth(request);
  const db = getFirestore();
  const bucket = getStorage().bucket();
  const { ref, snap } = await loadMatterForUser(db, uid, (request.data || {}).matterId, P.DEFAULT_FIRM_ID.value());
  const md = snap.data() || {};
  const { receipts, chain } = await loadMatterData(db, ref);
  const exportedAt = new Date();
  const exportedBy = await generatedByName(db, uid, request);
  const title = md.matterName || md.caseTitle || ref.id;

  const exhibitName = ({ id, data: r }) => {
    if (!r.sourceStoragePath) return null;
    const seq = String(r.chainSeq || 0).padStart(3, '0');
    return `exhibits/${seq}-${safeName(r.originalFileName || `${id}${path.extname(r.sourceStoragePath)}`)}`;
  };
  const tsrName = ({ id, data: r }) => (r.tsaTokenPath ? `timestamps/${String(r.chainSeq || 0).padStart(3, '0')}-${id}.tsr` : null);
  const manifest = buildManifest({ matterId: ref.id, matter: md, receipts, chain, exportedAt, exportedBy, exhibitFor: exhibitName, tsrFor: tsrName });

  let certificate = null;
  try {
    const verification = verifyEntries([...chain].sort((a, b) => (a.seq || 0) - (b.seq || 0)));
    certificate = await buildRecordPdf({
      matter: {
        id: ref.id,
        title,
        clientName: md.clientName || '',
        caseNumber: md.caseNumber || '',
        assignedCounsel: md.assignedCounsel || '',
        practiceArea: md.practiceArea || '',
        openedAt: toDate(md.openedAt),
        redactionCount: md.redactionCount || 0,
        redactionCategories: md.redactionCategories || '',
        hashChainLastAnchoredAt: toDate(md.hashChainLastAnchoredAt),
        chainHeadHash: md.chainHeadHash || '',
      },
      receipts: pdfReceipts(receipts),
      chain: [...chain]
        .sort((a, b) => (a.seq || 0) - (b.seq || 0))
        .map((e) => ({ seq: e.seq, prevHash: e.prevHash || '', itemHash: e.itemHash || '', receivedAtIso: e.receivedAtIso || '', originDigest: e.originDigest || '', entryHash: e.entryHash || '' })),
      verification,
      generatedAt: exportedAt,
      generatedBy: exportedBy,
    });
  } catch (e) {
    console.error('exportRecordZip: certificate failed', e);
  }

  const stamp = exportedAt.toISOString().replace(/[-:]/g, '').replace(/\.\d+Z$/, 'Z');
  const fileName = `${slug(title)}-record-${stamp}.zip`;
  const storagePath = `matters/${ref.id}/exports/${fileName}`;
  const { zip, out } = makeZip();
  const saved = saveStream(bucket, storagePath, out, 'application/zip', fileName, uid);

  zip.append(JSON.stringify(manifest, null, 2), { name: 'manifest.json' });
  zip.append(readmeText(manifest), { name: 'README.txt' });
  zip.append(fs.readFileSync(path.join(__dirname, 'verify.py')), { name: 'verify.py', mode: 0o755 });
  if (certificate) zip.append(certificate, { name: 'certificate.pdf' });
  let exhibits = 0;
  for (const r of receipts) {
    const name = exhibitName(r);
    if (name) {
      const f = bucket.file(r.data.sourceStoragePath);
      const [exists] = await f.exists();
      if (exists) {
        await appendAndWait(zip, () => f.createReadStream(), name);
        exhibits++;
      }
    }
    const t = tsrName(r);
    if (t) {
      const tf = bucket.file(r.data.tsaTokenPath);
      const [texists] = await tf.exists();
      if (texists) await appendAndWait(zip, () => tf.createReadStream(), t);
    }
  }
  await zip.finalize();
  const result = await saved;

  await ref.collection('exports').add({
    kind: 'record_zip',
    storagePath,
    fileName,
    sha256: result.sha256,
    bytes: result.bytes,
    items: receipts.length,
    exhibits,
    chainHead: manifest.chain_head,
    chainOk: manifest.chain_verification_at_export.ok,
    generatedByUid: uid,
    generatedAt: FieldValue.serverTimestamp(),
  });

  return { downloadUrl: result.downloadUrl, fileName, sha256: result.sha256, items: receipts.length, exhibits, storagePath };
});

exports.exportFirmData = onCall({ timeoutSeconds: 540, memory: '1GiB' }, async (request) => {
  const uid = requireAuth(request);
  const db = getFirestore();
  const bucket = getStorage().bucket();
  const firmId = await firmIdForUser(db, uid, P.DEFAULT_FIRM_ID.value());
  const mattersSnap = await db.collection('Matters').where('firmID', '==', firmId).get();
  const exportedAt = new Date();
  const exportedBy = await generatedByName(db, uid, request);

  const stamp = exportedAt.toISOString().replace(/[-:]/g, '').replace(/\.\d+Z$/, 'Z');
  const fileName = `verin-export-${slug(firmId)}-${stamp}.zip`;
  const storagePath = `exports/${slug(firmId)}/${fileName}`;
  const { zip, out } = makeZip();
  const saved = saveStream(bucket, storagePath, out, 'application/zip', fileName, uid);

  const index = [];
  for (const m of mattersSnap.docs) {
    const { receipts, chain } = await loadMatterData(db, m.ref);
    const manifest = buildManifest({ matterId: m.id, matter: m.data(), receipts, chain, exportedAt, exportedBy });
    const folder = `${slug(manifest.matter.name || m.id)}-${m.id.slice(0, 6)}`;
    zip.append(JSON.stringify(manifest, null, 2), { name: `${folder}/manifest.json` });
    index.push({ id: m.id, name: manifest.matter.name, receipts: manifest.receipts.length, chain_head: manifest.chain_head, folder });
  }
  zip.append(JSON.stringify({ exported_at: exportedAt.toISOString(), exported_by: exportedBy, firm: firmId, matters: index }, null, 2), { name: 'index.json' });
  zip.append(
    'Verin firm data export: one folder per matter with its manifest (receipts, hashes, hash chain).\nExhibit files are not included; export a single matter\'s record ZIP for those.\n',
    { name: 'README.txt' },
  );
  await zip.finalize();
  const result = await saved;
  return { downloadUrl: result.downloadUrl, fileName, matters: index.length, sha256: result.sha256 };
});

// ---------------------------------------------------------------------------
// Integration report PDF
// ---------------------------------------------------------------------------

function buildIntegrationReportPdf({ matter, receipts, clio, generatedAt, generatedBy }) {
  const PDFDocument = require('pdfkit');
  const { NAVY, TEAL, INK, MUTED, RULE } = COLORS;
  const doc = new PDFDocument({ size: 'LETTER', layout: 'landscape', margins: { top: 48, bottom: 56, left: 48, right: 48 }, bufferPages: true });
  doc.registerFont('Sans', FONTS.sans);
  doc.registerFont('Bold', FONTS.bold);
  doc.registerFont('Mono', FONTS.mono);
  doc.registerFont('Serif', FONTS.serif);
  const chunks = [];
  doc.on('data', (c) => chunks.push(c));
  const done = new Promise((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
  const left = doc.page.margins.left;
  const width = doc.page.width - left - doc.page.margins.right;
  const bottom = () => doc.page.height - doc.page.margins.bottom;

  doc.rect(left, doc.y, width, 64).fill(NAVY);
  const top = doc.y;
  doc.font('Bold').fontSize(8).fillColor('#E4EEEF').text('VERIN EVIDENCE RECORD', left + 18, top + 14, { characterSpacing: 1.6 });
  doc.font('Serif').fontSize(18).fillColor('#FBFAF8').text('Integration Report', left + 18, top + 28);
  doc.font('Sans').fontSize(9).fillColor('#E4EEEF').text(`Generated ${human(generatedAt)}\nby ${printable(generatedBy)}`, left, top + 18, { width: width - 18, align: 'right' });
  doc.y = top + 80;

  const kv = [
    ['Matter', matter.title],
    ['Client', matter.clientName],
    ['Cause number', matter.caseNumber],
    ['Evidence items', `${receipts.length} total · ${receipts.filter((r) => r.state === 'Processed').length} processed`],
    ['Chain head', matter.chainHeadHash],
  ];
  for (const [k, v] of kv) {
    const y = doc.y;
    doc.font('Sans').fontSize(9).fillColor(MUTED).text(k, left, y, { width: 120 });
    doc.font(k === 'Chain head' ? 'Mono' : 'Sans').fontSize(k === 'Chain head' ? 8 : 10).fillColor(INK).text(printable(dash(v)), left + 120, y, { width: width - 120 });
    doc.moveDown(0.3);
  }
  doc.moveDown(0.6);

  const section = (name, synced, sub, rows, emptyNote) => {
    if (doc.y + 60 > bottom()) doc.addPage();
    doc.moveTo(left, doc.y).lineTo(left + width, doc.y).lineWidth(0.5).strokeColor(RULE).stroke();
    doc.moveDown(0.5);
    doc.font('Bold').fontSize(11).fillColor(INK).text(name, left, doc.y, { continued: true });
    doc.font('Sans').fontSize(9).fillColor(synced ? TEAL : MUTED).text(`   ${synced ? 'Synced' : 'Not synced'} · ${sub}`);
    doc.moveDown(0.4);
    if (!synced || !rows.length) {
      doc.font('Sans').fontSize(9).fillColor(MUTED).text(emptyNote, left, doc.y, { width });
      doc.moveDown(0.8);
      return;
    }
    const cols = [
      ['Content', 0.34],
      ['Kind', 0.1],
      ['Received', 0.14],
      ['SHA-256 at receipt', 0.21],
      ['Chain entry', 0.21],
    ];
    const header = () => {
      let x = left;
      const y = doc.y;
      for (const [c, w] of cols) {
        doc.font('Bold').fontSize(7.5).fillColor(MUTED).text(c.toUpperCase(), x, y, { width: width * w - 6 });
        x += width * w;
      }
      doc.moveDown(0.5);
    };
    header();
    for (const r of rows) {
      const cells = [r.headline, r.itemKind, human(r.receivedAt), r.itemHash, r.entryHash];
      const heights = cells.map((v, i) => {
        doc.font(i >= 3 ? 'Mono' : 'Sans').fontSize(i >= 3 ? 7 : 8.5);
        return doc.heightOfString(printable(dash(v)), { width: width * cols[i][1] - 6 });
      });
      const h = Math.max(...heights) + 6;
      if (doc.y + h > bottom()) {
        doc.addPage();
        header();
      }
      const y = doc.y;
      let x = left;
      cells.forEach((v, i) => {
        doc.font(i >= 3 ? 'Mono' : 'Sans').fontSize(i >= 3 ? 7 : 8.5).fillColor(INK).text(printable(dash(v)), x, y, { width: width * cols[i][1] - 6 });
        x += width * cols[i][1];
      });
      doc.y = y + h;
    }
    doc.moveDown(0.8);
  };

  const processed = receipts.filter((r) => r.state === 'Processed');
  section(
    'Clio Manage',
    clio.synced,
    clio.matchedTo ? `matched to ${clio.matchedTo}` : 'not matched',
    processed,
    clio.matchedTo ? 'Matched — push the record from the Practice tab to sync it.' : 'Not connected.',
  );
  section('MyCase', false, 'coming soon', [], 'Coming soon — needs partner approval from MyCase.');
  section('Smokeball', false, 'coming soon', [], 'Coming soon.');

  doc.moveDown(0.5);
  doc.font('Sans').fontSize(8).fillColor(MUTED).text(
    'Each push uploads a newly generated record; earlier uploads stay in the practice system. A failed push is treated as a trust incident and surfaced in Verin. Verin offers no opinion on authenticity, completeness or admissibility.',
    left,
    doc.y,
    { width },
  );

  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.font('Sans').fontSize(7.5).fillColor(MUTED).text(`Verin integration report · ${printable(matter.title)} · page ${i + 1} of ${range.count}`, left, doc.page.height - 36, { width, align: 'center' });
  }
  doc.end();
  return done;
}

exports.exportIntegrationReport = onCall({ timeoutSeconds: 120, memory: '1GiB' }, async (request) => {
  const uid = requireAuth(request);
  const db = getFirestore();
  const bucket = getStorage().bucket();
  const { ref, snap } = await loadMatterForUser(db, uid, (request.data || {}).matterId, P.DEFAULT_FIRM_ID.value());
  const md = snap.data() || {};
  const { receipts } = await loadMatterData(db, ref);
  const generatedAt = new Date();
  const generatedBy = await generatedByName(db, uid, request);
  const title = md.matterName || md.caseTitle || ref.id;
  const rows = receipts
    .filter(({ data: r }) => r.isDuplicate !== true)
    .map(({ data: r }) => ({
      headline: headlineOf(r),
      itemKind: r.itemKind || '',
      receivedAt: toDate(r.receivedAt),
      itemHash: r.item_hash || '',
      entryHash: r.entryHash || '',
      state: r.classificationLabel || 'Processed',
    }))
    .sort((a, b) => (a.receivedAt ? a.receivedAt.getTime() : 0) - (b.receivedAt ? b.receivedAt.getTime() : 0));
  const clioRef = md.clioMatterID || md.providerMatterReference || '';
  const pdf = await buildIntegrationReportPdf({
    matter: { title, clientName: md.clientName || '', caseNumber: md.caseNumber || '', chainHeadHash: md.chainHeadHash || '' },
    receipts: rows,
    clio: { synced: !!md.clioSyncedAt && !!clioRef, matchedTo: md.clioMatterDisplayNumber || clioRef },
    generatedAt,
    generatedBy,
  });
  const sha256 = crypto.createHash('sha256').update(pdf).digest('hex');
  const stamp = generatedAt.toISOString().replace(/[-:]/g, '').replace(/\.\d+Z$/, 'Z');
  const fileName = `${slug(title)}-integration-report-${stamp}.pdf`;
  const storagePath = `matters/${ref.id}/exports/${fileName}`;
  const token = crypto.randomUUID();
  await bucket.file(storagePath).save(pdf, {
    resumable: false,
    contentType: 'application/pdf',
    metadata: { contentDisposition: `inline; filename="${fileName}"`, metadata: { firebaseStorageDownloadTokens: token, sha256, generatedBy: uid } },
  });
  return {
    downloadUrl: `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(storagePath)}?alt=media&token=${token}`,
    fileName,
    sha256,
  };
});

module.exports.buildManifest = buildManifest;
module.exports.readmeText = readmeText;
module.exports.buildIntegrationReportPdf = buildIntegrationReportPdf;
